from io import BytesIO
from reportlab.pdfgen import canvas
from django.http import HttpResponse

import email, smtplib, ssl

from email import encoders
from email.mime.base import MIMEBase
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

c = canvas.Canvas('automate_report.pdf')
c.setFillColorRGB(1,1,0)
c.setFont('Helvetica', 30)
c.drawSting(5, 660,'Missing data chart for Titanic Data')
c.drawString(5, 630, 'Report generated by Python')
c.drawImage('Survival.png', 5,90,480,400)
c.showPage()
c.save()

subject = "weekly report"
body = "This is an email with the desired report attached"
